
test:
    go test ./...

lint:
    golangci-lint run ./...

build:
    go build -o kubernetes-openapi .

install:
    dest=$(go env GOBIN); [ -n "$dest" ] || dest=$(go env GOPATH)/bin; go build -o "$dest/kubernetes-openapi" .

test-e2e:
    KUBERNETES_OPENAPI_BINARY="$(pwd)/kubernetes-openapi" go test -v -tags e2e ./tests/...

ci: lint test build test-e2e
